# Generated by Django 5.2.6 on 2026-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greanleaf_app', '0002_alter_favorite_unique_together_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
