# Generated by Django 5.2.6 on 2026-06-13 22:39

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greanleaf_app', '0003_order_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', multiselectfield.db.fields.MultiSelectField(choices=[('ПН', 'ПН'), ('ВТ', 'ВТ'), ('СР', 'СР'), ('ЧТ', 'ЧТ'), ('ПТ', 'ПТ'), ('СБ', 'СБ'), ('ВС', 'ВС')], max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutAsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='greanleaf_app.aboutus')),
            ],
        ),
    ]
