# Generated by Django 5.2.6 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greanleaf_app', '0005_aboutus_description_ky_aboutus_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('seller', 'seller'), ('client', 'client')], default='client', max_length=10),
        ),
    ]
